language: node_js
node_js:
  - "iojs"
  - "7"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
before_script:
  - yarn
script:
  - yarn test
